apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.service.name }}
  labels:
    run: {{ .Release.Name }}
  namespace: {{ .Release.namespace }}
spec:
  selector:
    app: {{ .Release.Name }}
  ports:
  - name: http
    port: {{ .Values.container.port }}
    targetPort: {{ .Values.container.port }}
    protocol: TCP