stages:
  - build
  - package
  - deploy

include: 'version.yaml'

variables:
  NAME: user-docs
  FQ_IMAGE_NAME: "$CI_REGISTRY_IMAGE/$NAME:latest"
  # The FQIN with Version variable below is not currently used; meant to be used so we have latest and a version to return to
  FQ_IMAGE_NAME_W_VERSION: "$CI_REGISTRY_IMAGE/$NAME:$VERSION"

package:
  stage: package
  image: docker:26.1.4
  before_script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - docker builder prune -f
  script:
    - docker build -t $FQ_IMAGE_NAME --build-arg SRC=$CI_PROJECT_DIR -f $CI_PROJECT_DIR/deploy/docker/Dockerfile .
    - docker push $FQ_IMAGE_NAME
  rules:
    - if: $CI_COMMIT_BRANCH == "docs"
      when: manual

deploy:
  stage: deploy
  image: 
    name: alpine/helm:3.14.4
    entrypoint: ['']
  script:
    - helm uninstall  $NAME -n user-docs --kube-context="solo-laboratories/development/ReleaseGenerator:local-cluster" || true
    - helm upgrade --install $NAME $CI_PROJECT_DIR/deploy/helm -n user-docs --create-namespace --atomic --kube-context="solo-laboratories/development/ReleaseGenerator:local-cluster" --timeout 1m0s
  rules:
    - if: $CI_COMMIT_BRANCH == "docs"
      when: manual  