stages:
  - build
  - package
  - deploy

variables:
  FQ_IMAGE_NAME: "$CI_REGISTRY_IMAGE/user-docs:latest"
  # The FQIN with Version variable below is not currently used; meant to be used so we have latest and a version to return to
  FQ_IMAGE_NAME_W_VERSION: "$CI_REGISTRY_IMAGE/user-docs:0.0.1"

package:
  stage: package
  image: docker:24.0.5
  before_script:
    - docker login -u $CI_DEPLOY_USER -p $CI_DEPLOY_PASSWORD $CI_REGISTRY
    - docker builder prune -f
  script:
    - docker build -t $FQ_IMAGE_NAME .
    - docker push $FQ_IMAGE_NAME
  rules:
    # - if: $CI_COMMIT_BRANCH == "docs"
    - when: manual

deploy:
  stage: deploy
  image: 
    name: alpine/helm:3.14.4
    entrypoint: ['']
  script:
    - helm uninstall user-docs -n release-generator --kube-context=""
    - helm upgrade --install user-docs -n release-generator --atomic --kube-context="" --timeout 1m0s
  rules:
    # - if: $CI_COMMIT_BRANCH == "docs"
    - when: manual
